# DBSCAN

This algorithm defines clusters as continuous regions of high density.

Here is how it works:

* For each instance, the algorithm counts how many instances are located within a small distance $\epsilon$ (epsilon) from it. This region is called the instance's $\epsilon-neighborhood$.
* If an instance has at least *min_samples* instances in its $\epsilon-neighborhood$ (including itself), then it is considered a core instances. In other words, core instances are those that are located in dense regions.
* All instances in the neighborhood of a core instance belong to the same cluster. This neighborhood may include other core instances; therfore, a  long sequence of neighboring core instances forms a single cluster.
* Any instance that is not a core instance and does not have one in its neighborhood is considered an anomaly.

In [1]:
import numpy as np
from sklearn.datasets import make_moons
from sklearn.cluster import DBSCAN

In [2]:
X, y = make_moons(n_samples = 1000, noise = 0.05, random_state = 42)

In [3]:
dbscan = DBSCAN(eps = 0.05, min_samples = 5)
dbscan.fit(X)

DBSCAN(eps=0.05)

In [4]:
dbscan.labels_[:10]

array([ 0,  2, -1, -1,  1,  0,  0,  0,  2,  5])

Notice that some instances have a cluster index equal to -1, which means that they are considered as anomalies by algorigm.

In [5]:
# the indices of the core instances

len(dbscan.core_sample_indices_)

808

In [6]:
dbscan.core_sample_indices_[:10]

array([ 0,  4,  5,  6,  7,  8, 10, 11, 12, 13])

In [7]:
# core instances themselves

dbscan.components_[:3]

array([[-0.02137124,  0.40618608],
       [-0.84192557,  0.53058695],
       [ 0.58930337, -0.32137599]])

In [8]:
dbscan2 = DBSCAN(eps = 0.2)
dbscan2.fit(X)

DBSCAN(eps=0.2)

Somewhat surprisingly, the DBSCAN class does not have a *predict()* method, although it has a *fit_predict()* method. In other words, it cannot predict which cluster a new instance belongs to. This implementation decision was made because different classification algorithms can be better for different tasks.

In [9]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 50)
knn.fit(dbscan2.components_, dbscan2.labels_[dbscan2.core_sample_indices_])

KNeighborsClassifier(n_neighbors=50)

Now, given a few new instances, we can predict which cluster they most likeky belong to and even estimate a probability for each cluster:

In [10]:
X_new = np.array([[-0.5, 0], [0, 0.5], [1, -0.1], [2, 1]])
knn.predict(X_new)

array([1, 0, 1, 0])

In [11]:
knn.predict_proba(X_new)

array([[0.18, 0.82],
       [1.  , 0.  ],
       [0.12, 0.88],
       [1.  , 0.  ]])

In short, DBSCAN is a very simple yet powerful algorithm capable of identifying any number of clusters of any shape. It is robust to outliers, and it has just two hyperparameters (eps and min_samples).